version: "3.8"
services:

  ansible:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-controller
    hostname: ansible
    tty: true
    volumes:
      - ./ansible:/ansible

  web01:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: web01

  web02:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: web02
  
  web03:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: web03

  web04:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: web04

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: api

  db-data:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: db-data

  db-cache:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: db-cache
