version: "3.8"
services:

  ansible:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-controller
    hostname: ansible
    tty: true
    volumes:
      - ./shared-folder:/shared-folder

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: web

  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: db
  
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: gateway

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: ansible-host
    hostname: test
